# Generated by Django 5.1.4 on 2025-01-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
